import Sidebar from "@/ui/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '../../ui/Header';
import Footer from "@/ui/Footer";
import dashboardStyle from '@/styles/dashboard.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard CMS App",
  description: "Generated by vk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dashboardStyle.body__wrapper}`}>
        <div className={`${dashboardStyle.boday__area__wrapper}`}>
        <div className={`${dashboardStyle.flex__one__child} ${dashboardStyle['max-vh-100']} ${dashboardStyle.nav__bar__bg__color} ${dashboardStyle['p-20']}`} ><Sidebar /></div>
        <div className={`main__area_wrapper ${dashboardStyle.flex__four__child}`} >
            <Header />
            {children}
            <Footer/>
        </div>
        </div>
        </body>
    </html>
  );
}
